version: "3.9"

services:
  base:
    build: .
    volumes:
      - './:/opt/services/src'
    environment:
      - AUC_HOST=host.docker.internal
      - AUC_PORT=8000

  bidder_webapi1:
    extends:
      service: base
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084", "--reload"]
    ports:
       - "8084:8084"
    environment:
      - DELAY=100
      - BID_AMT=624
      - PORT=8084

  bidder_webapi2:
    extends:
      service: base
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8083", "--reload"]
    ports:
       - "8083:8083"
    environment:
      - DELAY=150
      - BID_AMT=700
      - PORT=8083

  bidder_webapi3:
    extends:
      service: base
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8082", "--reload"]

    ports:
       - "8082:8082"
    environment:
      - DELAY=250
      - BID_AMT=520
      - PORT=8082

  bidder_webapi4:
    extends:
      service: base
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081", "--reload"]

    ports:
       - "8081:8081"
    environment:
      - DELAY=170
      - BID_AMT=500
      - PORT=8081
